# Generated by Django 3.2.7 on 2021-09-14 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('prep_time', models.IntegerField(blank=True, default=None, null=True)),
                ('cook_time', models.IntegerField(blank=True, default=None, null=True)),
                ('total_time', models.IntegerField(blank=True, default=None, null=True)),
                ('servings', models.IntegerField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('ingredients', models.TextField(blank=True, default=None, null=True)),
                ('steps', models.TextField(blank=True, default=None, null=True)),
                ('nutrition', models.TextField(blank=True, default=None, null=True)),
                ('category', models.ManyToManyField(blank=True, default=None, to='recipes.Category')),
            ],
        ),
    ]
