# Generated by Django 3.2.7 on 2021-10-17 18:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20211017_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cloud_image',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
    ]
