# Generated by Django 3.2.7 on 2021-10-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20211017_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
